# Generated by Django 5.0.4 on 2024-04-17 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dishcategory_options_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='main.dishcategory'),
        ),
    ]
