# Generated by Django 5.0.4 on 2024-04-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dishcategory_slug_alter_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcategory',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
